config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'tasks', to: 'tasks#index'

  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :new_task

  get 'tasks/:id', to: 'tasks#show', as: :task

  patch 'tasks/:id', to: 'tasks#update'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# This controller manages tasks within the application.
# It handles CRUD operations for tasks and interacts with the database.
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %> Completed
  <%= f.submit %>
<% end %>

<div class="end-link">
  <i class="fa-solid fa-rotate-left"></i>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul style="list-style-type: none;">
  <% @tasks.each do |task| %>
    <li class="form-check">
      <input class="form-check-input" type="checkbox" <%= task.completed ? "checked" : " "%> aria-label="...">
      <label class="form-check-label" for=<%= "flexCheckDefault#{task.id}" %>>

        <%= link_to task.title, task_path(task) %> •

        <%= link_to destroy_path(task), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>

      </label>
    </li>
  <% end %>
</ul>

<i class="fa-solid fa-plus"></i>
<%= link_to "New task", new_task_path  %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_with model: @task do |f| %>
   <div class="card-body">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="card-body">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <%= f.submit %>
<% end %>

<div class="end-link">
  <a class="link-offset-2 link-underline link-underline-opacity-0" href="#">
    <i class="fa-solid fa-rotate-left"></i>
    <%= link_to "Back to list", tasks_path %>
  </a>
</div>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= link_to "Edit this task", edit_task_path() %></p>

<p><%= @task.details %></p>

<input class="form-check-input" type="checkbox" <%= @task.completed ? "checked" : " "%> aria-label="...">
<span id="completion_status_text"><%= @task.completed ? "This task is completed" : "This task is not completed" %></span>


<div class="end-link">
  <i class="fa-solid fa-rotate-left"></i>
  <%= link_to "Back to list", tasks_path %>
</div>